# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"

unbind = SUPER, SHIFT, PRINT
bindd = SUPER SHIFT, S, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard

unbind = SUPER SHIFT, M
unbind = SUPER SHIFT, N
unbind = SUPER SHIFT, D
unbind = SUPER SHIFT, G
unbind = SUPER SHIFT, O
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, SLASH
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT ALT, A
unbind = SUPER SHIFT, C
unbind = SUPER SHIFT, E
unbind = SUPER SHIFT, Y
unbind = SUPER SHIFT ALT, G
unbind = SUPER SHIFT CTRL, G
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, X
unbind = SUPER SHIFT ALT, X
unbind = SUPER CTRL ALT, Z
unbind = SUPER CTRL, Z
