
# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 3
    gaps_out = 7
    border_size = 1

    # Use master layout instead of dwindle
    # layout = master
}
# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5
    
    blur {
        enabled = yes
        size = 5
        passes = 3
        ignore_opacity = true

        noise  = 0.03
        contrast = 1.5

        xray = false
        new_optimizations = true

      }
  active_opacity = 0.8
}

input {
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
    }
    sensitivity = 0.2
}

